### ISSUE TITLE
Game crashed when entered the game.

### ISSUE THREAD

**Issue by izumirem** [nuclearsilo583/zephyrus-store-preview-new-syntax#12]
Hello,Thank you for your store. I have encountered an error when connect to the server
![E78UG$RF@VJZZ_PBMICT}N4](https://user-images.githubusercontent.com/83826366/117463220-03d78f80-af82-11eb-9dfb-b9aecf89008c.png)
The game client crashed when these error happened.
I never got this error when i test these models. I may not have noticed it, but it didn't crash before. These errors occurred after today's update
Other plugins run on the server : S-Downloader, Arm-fix.
This is my "items.txt" file  :  https://github.com/izumirem/items/blob/main/items.txt
Wish you can help me ,thank you.

**Comment by nuclearsilo583** [comment]
You can look for this [post](https://forums.alliedmods.net/showthread.php?t=310768).
1. Try to lower setting to low.
2. Bad models can cause strange client crashes
3. Delete all entry from line 88 to 98 in [this](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/scripting/store_item_playerskins.sp). Since you are using S downloader so dont need to re-precache model on plugin
4. Bad materials also cause this crash.
p/s: too many models, materials precache can cause client to crash (not the server)

**Comment by izumirem** [comment]
thank you very much,I will try it later.

**Comment by izumirem** [comment]
Hi,there is another trouble. This problem occurred in the map after I added 27 models.
![61854a7f65bc074c](https://user-images.githubusercontent.com/83826366/117561624-ed891b00-b0ca-11eb-8a35-2168c758cd0a.png)
See, the grass is bright.(Actually，not only grass have this problem.)
I try to lower setting to medium,but it doesn't work.
I try to not precache materials,it doesn't work,too.

**Comment by izumirem** [comment]
Ok! Many thanks for your kind help！
