### ISSUE TITLE
Cannot load plugins in tf2, requires cs extension

### ISSUE THREAD

**Issue by zryuek** [nuclearsilo583/zephyrus-store-preview-new-syntax#180]
[SM] Plugin store_item_playerskins.smx failed to load: Required extension "cstrike" file("games/game.cstrike.ext") not running.
Almost all plugins requires cstrike.ext, causing them to not work. Loading the tf2 module beforehand does not help.

**Comment by vicentefelipechile** [comment]
what do you do to fix it?

**Comment by nuclearsilo583** [comment]
> what do you do to fix it?

Some plugin has #include <cstrike> in .sp
You just need to remove it then recompile. Please note some plugin may not work probably in tf2 so check out the tf2 modules folder that was written for specific game only
For this issue post it seem he had problem with playerskin module since that module is for csgo. 
For tf2 playerskin check this repo: https://github.com/HotoCocoaco/zephyrus-store-preview-new-syntax
