### ISSUE TITLE
Have more module for cs:s?

### ISSUE THREAD

**Issue by Power28** [nuclearsilo583/zephyrus-store-preview-new-syntax#21]
Hello there? it's there have more module support cs:s or just pet and playermodel~~
And my pet will show like this
![未命名](https://user-images.githubusercontent.com/26226304/127869683-1c66f3e8-e83d-4677-90ad-458001f79d9e.jpg)
it's not support for css?

And i got this error
![未命名](https://user-images.githubusercontent.com/26226304/127870428-70401d6e-7c82-4581-98b7-90649d63033c.jpg)
is this normal?

thx for answer~

**Comment by nuclearsilo583** [comment]
1: Yes there are more module that you can use beside modules the in `css_modules_reworked`. Simply just install any that you want in the main scripting folder and use it. You may have some error due that modules didn't get reworked yet. Please tell me if you want to rework it to use in CSS.
2: The black and purple you saw is mainly have 2 reason.
- You are missing materials for that model (this option is not the case since you downloaded my models and materials)
- The version of your materials (vtf) is above 7.2. To fix this problem simply import all the texture file (vtf) to 7.2 version. [Youtube](https://www.youtube.com/watch?v=CcZeknXK0P8&t=7s) at 10:10. There's a advanced tab. Change version to 7.2 and everything should be good to go.
![image](https://user-images.githubusercontent.com/58926275/128000718-189db624-9472-4018-8660-da0d3547d1d7.png)

P/s: for the error you got i forget css dont have gloves like csgo. You want to remove this [line](https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/scripting/css_modules_reworked/store_item_playerskins_no_zr_version_css.sp#L272)

**Comment by Power28** [comment]
it's perfectly fix thx for answer~~
