### ISSUE TITLE
Inventory Glitch

### ISSUE THREAD

**Issue by ParzivalGG** [nuclearsilo583/zephyrus-store-preview-new-syntax#33]
If somebody is buying custom weapon models, then it works for that particular period and afterwards when they join again their inventory is gone, and they've to buy it again.

**Comment by nuclearsilo583** [comment]
If you using mysql as database. Can you give me a screenshot at the time player buy an item in the store_plugins_log table

**Comment by ParzivalGG** [comment]
![image](https://user-images.githubusercontent.com/91301500/135389950-c576dfa0-ae45-4ff0-81f2-3e01bfd60a49.png)
There ya go!

**Comment by ParzivalGG** [comment]
![image](https://user-images.githubusercontent.com/91301500/135390042-11519f35-b354-49d6-837a-904e3f7f30c1.png)

**Comment by KillerRoi** [comment]
It is still not saving

**Comment by KillerRoi** [comment]
Everytime, players need to join and equip it again and again

**Comment by Oz-Lin** [comment]
Sorry for necroing.
This happens when the previous `playerskin` was expired but not removed from `store_equipment` database table.
Everytime when a player reports the store bug to me, I have to remove the loadout from the database manually.

```
L 08/23/2022 - 02:23:20: [store.smx] SQL error happened.
Query: INSERT INTO store_equipment (`player_id`, `type`, `unique_id`, `slot`) VALUES(438, "playerskin", "uid_model_megumin", 2)
Error: Duplicate entry '438-playerskin-2' for key 'PRIMARY'
```

**Comment by nuclearsilo583** [comment]
Can you give me screenshot me the store_equipment table structure.

**Comment by Oz-Lin** [comment]
Here you go.
![图片](https://user-images.githubusercontent.com/36224575/186314901-988d8fb5-65ab-4d30-afd7-e8ea22113d89.png)

**Comment by nuclearsilo583** [comment]
probaly you have done something to that table because the table doesn't contain any primary keys and unique key which make the data can't insert duplicate. This is how the structure from myside even with the fresh/ currently created table. You should backup the store_equipment table and drop it via mysql. And restart the server so it can create that table again with the most exact sync.
![image](https://user-images.githubusercontent.com/58926275/186325789-554609d8-b5c6-4d44-b554-14106a024c30.png)

**Comment by Oz-Lin** [comment]
Thanks, hopefully the problem is solved after moving values from the old store_equipment to the new one.
