### ISSUE TITLE
[Feature Request] Daily Credits support for MySQL

### ISSUE THREAD

**Issue by Bernardino18** [nuclearsilo583/zephyrus-store-preview-new-syntax#69]
Issue: Server owners with multiple servers, players can redeem credits per server.

https://github.com/nuclearsilo583/zephyrus-store-preview-new-syntax/blob/master/addons/sourcemod/scripting/store_misc_earnings.sp

**Comment by azalty** [comment]
This plugin currently uses the cookies database & functions to store wether the client got their daily credits.

The best solution in my opinion is to create a ConVar that is empty by default, and in which owners can specify a database config name.
- If a database config name is used, player data will be loaded through this DB.
- If the string is empty, use cookies instead.

Shouldn't be too hard to do, but would require writing database specific functions instead of using the easy cookies method.

I can do it if wanted.

**Comment by Bernardino18** [comment]
Yes, i agree @azalty

**Comment by azalty** [comment]
Just saw that the cookie system can be exploited by players to reset their last daily claim and thus, get infinite daily claims with no delay.

I'll fix this issue and do your request.

**Comment by azalty** [comment]
Boom, pull request! #70 

Could you please try the changes @Bernardino18 ?

**Comment by Bernardino18** [comment]
Yes, live on two game servers (csgo) 10 hours ago.
It is working

**Comment by azalty** [comment]
Thanks for your feedback!
